### ISSUE TITLE
Can't change ChargeItemNameTier: ID

### ISSUE THREAD

**Issue by Kixot14** [ColbyLeclerc/FlyPayment#1]
Can't change ChargeItemNameTier: ID!  When tried to change - this just update config and put on "OldConfig"

.....And custom message to!
Cant change nothing!

In console have error: Configuration files out of date. Loading new configuration file...

Spigot v1.8.3
FlyP: v3.5_BETA_2

**Comment by ColbyL** [comment]
The project, as it currently stands, is over a year old. With that said, Minecraft has changed a lot in the past year and has probably broken the plugin with deprecated methods and such. I may rewrite the plugin (again) with a focus on spigot, and post the results to dev.bukkit.org.
